apiVersion: v2
name: prometheus
description: A Helm chart to deploy Prometheus, Alertmanager and Grafana
type: application
version: 0.1.0
appVersion: 42.0.0

dependencies:
- name: kube-prometheus-stack
  alias: stack
  version: 42.0.0
  repository: "https://prometheus-community.github.io/helm-charts"
