apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  nginx.conf: |
    server {
      listen       8080;
      server_name  frontend;

      location /status {
          stub_status;
      }
    }
