apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  default.conf: |
    server {
      listen       80;
      server_name  frontend;

      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }

      location /nginx_status {
          stub_status;
      }
    }
