apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    release: monitor
spec:
  endpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      app: frontend