apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/agalue/tutorial-argocd.git
    targetRevision: HEAD
    path: helm/prometheus
    # helm:
    #   valueFiles:
    #   - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Validate=false
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /status
